#!/bin/sh
set -e

# Disabled because macros will fail.
# Automatically added by dh_python3:
#if which py3compile >/dev/null 2>&1; then
#	py3compile -p kiplot.inti-cmnb -V 3.2-
#fi
#if which pypy3compile >/dev/null 2>&1; then
#	pypy3compile -p kiplot.inti-cmnb -V 3.2- || true
#fi

# End automatically added section
