#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Copyright (c) 2020 Salvador E. Tropea
# Copyright (c) 2020 Instituto Nacional de Tecnología Industrial
# Copyright (c) 2018 John Beard
# License: GPL-3.0
# Project: KiBot (formerly KiPlot)
# Adapted from: https://github.com/johnbeard/kiplot
"""
    @package
    KiPlot - KiCad Python API plotter

    KiPlot is a program which helps you to plot your KiCad PCBs to output
    formats easily, repeatable, and most of all, scriptably. This means you
    can use a Makefile to export your KiCad PCBs just as needed.

"""

import sys
import os

here = os.path.abspath(os.path.dirname(__file__))
sys.path.insert(0, os.path.dirname(here))

from kibot.__main__ import main

main()
